import { Request, Response } from "express";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import User from "../models/User";

const ALLOWED_ROLES = ["user", "member", "st-member", "manager", "admin"];
const ALLOWED_STATUSES = ["active", "blocked"];

const sanitizeUser = (user: any) => {
  const obj = user.toObject ? user.toObject() : user;
  delete obj.password;
  delete obj.otp;
  delete obj.otpExpires;
  return obj;
};

const generateSecurePassword = (length = 12) => {
  const charset = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz0123456789!@#$%^&*";
  const bytes = crypto.randomBytes(length);
  let password = "";
  for (let i = 0; i < length; i += 1) {
    const index = bytes[i] % charset.length;
    password += charset[index];
  }
  return password;
};

// ------------------------------------------------------
// GET ALL USERS (Admin)
// ------------------------------------------------------
export const getAllUsers = async (req: any, res: Response) => {
  try {
    const users = await User.find()
      .select("-password -otp -otpExpires")
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      users,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: "Server error" });
  }
};

// ------------------------------------------------------
// GET SINGLE USER BY ID (Admin)
// ------------------------------------------------------
export const getUserById = async (req: Request, res: Response) => {
  try {
    const user = await User.findById(req.params.id).select("-password -otp -otpExpires");

    if (!user) {
      return res.status(404).json({ success: false, message: "User not found" });
    }

    res.json({ success: true, user });
  } catch (error) {
    res.status(500).json({ success: false, message: "Server error" });
  }
};

// ------------------------------------------------------
// CREATE USER (Admin)
// ------------------------------------------------------
export const createUser = async (req: Request, res: Response) => {
  try {
    const {
      name,
      email,
      role = "user",
      status = "active",
      password,
      first_name,
      last_name,
      phone,
      business,
      instagram,
      facebook,
      category,
      portfolio,
      country,
      state,
      city,
    } = req.body;

    if (!email) {
      return res.status(400).json({ success: false, message: "Email is required" });
    }

    const normalizedRole = typeof role === "string" ? role : "user";
    if (!ALLOWED_ROLES.includes(normalizedRole)) {
      return res.status(400).json({
        success: false,
        message: `Invalid role. Must be one of: ${ALLOWED_ROLES.join(", ")}`,
      });
    }

    const normalizedStatus = typeof status === "string" ? status : "active";
    if (!ALLOWED_STATUSES.includes(normalizedStatus)) {
      return res.status(400).json({
        success: false,
        message: "Invalid status. Must be either active or blocked",
      });
    }

    const existing = await User.findOne({ email: email.toLowerCase() });
    if (existing) {
      return res.status(409).json({
        success: false,
        message: "A user with this email already exists",
      });
    }

    let finalPassword = typeof password === "string" ? password.trim() : "";
    let autoGenerated = false;

    if (!finalPassword) {
      finalPassword = generateSecurePassword(12);
      autoGenerated = true;
    }

    if (finalPassword.length < 8) {
      return res.status(400).json({
        success: false,
        message: "Password must be at least 8 characters long",
      });
    }

    const hashedPassword = await bcrypt.hash(finalPassword, 12);

    const user = await User.create({
      name,
      email: email.toLowerCase(),
      password: hashedPassword,
      role: normalizedRole,
      status: normalizedStatus,
      first_name,
      last_name,
      phone,
      business,
      instagram,
      facebook,
      category,
      portfolio,
      country,
      state,
      city,
    });

    const createdUser = sanitizeUser(user);

    return res.status(201).json({
      success: true,
      message: "User created successfully",
      user: createdUser,
      tempPassword: autoGenerated ? finalPassword : undefined,
    });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || "Server error" });
  }
};

// ------------------------------------------------------
// UPDATE USER (Admin)
// ------------------------------------------------------
export const updateUser = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const updateData = req.body;

    // Don't allow password update through this route
    delete updateData.password;
    delete updateData.otp;
    delete updateData.otpExpires;

    const user = await User.findByIdAndUpdate(id, updateData, {
      new: true,
      runValidators: true,
    }).select("-password -otp -otpExpires");

    if (!user) {
      return res.status(404).json({ success: false, message: "User not found" });
    }

    res.json({ success: true, user, message: "User updated successfully" });
  } catch (error: any) {
    res.status(500).json({ success: false, message: error.message || "Server error" });
  }
};

// ------------------------------------------------------
// DELETE USER (Admin)
// ------------------------------------------------------
export const deleteUser = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;

    const user = await User.findById(id);

    if (!user) {
      return res.status(404).json({ success: false, message: "User not found" });
    }

    // Prevent deleting yourself
    if (req.user && req.user._id.toString() === id) {
      return res.status(400).json({ 
        success: false, 
        message: "You cannot delete your own account" 
      });
    }

    await User.findByIdAndDelete(id);

    res.json({ success: true, message: "User deleted successfully" });
  } catch (error) {
    res.status(500).json({ success: false, message: "Server error" });
  }
};

// ------------------------------------------------------
// CHANGE USER ROLE (Admin)
// ------------------------------------------------------
export const changeUserRole = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { role } = req.body;

    if (!ALLOWED_ROLES.includes(role)) {
      return res.status(400).json({ 
        success: false, 
      message: "Invalid role. Must be one of: user, member, st-member, manager, admin" 
      });
    }

    // Prevent changing your own role
    if (req.user && req.user._id.toString() === id) {
      return res.status(400).json({ 
        success: false, 
        message: "You cannot change your own role" 
      });
    }

    const user = await User.findByIdAndUpdate(
      id,
      { role },
      { new: true }
    ).select("-password -otp -otpExpires");

    if (!user) {
      return res.status(404).json({ success: false, message: "User not found" });
    }

    res.json({ 
      success: true, 
      user, 
      message: `User role changed to ${role}` 
    });
  } catch (error) {
    res.status(500).json({ success: false, message: "Server error" });
  }
};

// ------------------------------------------------------
// UPDATE USER STATUS (Admin)
// ------------------------------------------------------
export const updateUserStatus = async (req: any, res: Response) => {
  try {
    const { id } = req.params;
    const { status } = req.body;

    if (!status || !ALLOWED_STATUSES.includes(status)) {
      return res.status(400).json({
        success: false,
        message: "Invalid status. Must be either active or blocked",
      });
    }

    if (req.user && req.user._id.toString() === id) {
      return res.status(400).json({
        success: false,
        message: "You cannot change your own status",
      });
    }

    const user = await User.findByIdAndUpdate(
      id,
      { status },
      { new: true }
    ).select("-password -otp -otpExpires");

    if (!user) {
      return res.status(404).json({ success: false, message: "User not found" });
    }

    res.json({
      success: true,
      user,
      message: status === "blocked" ? "User blocked successfully" : "User unblocked successfully",
    });
  } catch (error) {
    res.status(500).json({ success: false, message: "Server error" });
  }
};

// ------------------------------------------------------
// GET USER STATS (Admin)
// ------------------------------------------------------
export const getUserStats = async (req: Request, res: Response) => {
  try {
    const totalUsers = await User.countDocuments();
    const adminUsers = await User.countDocuments({ role: "admin" });
    const managerUsers = await User.countDocuments({ role: "manager" });
    const regularUsers = await User.countDocuments({ role: "user" });
    const stMembers = await User.countDocuments({ role: "st-member" });
    const memberUsers = await User.countDocuments({ role: { $in: ["member", "st-member"] } });
    const blockedUsers = await User.countDocuments({ status: "blocked" });
    const activeUsers = await User.countDocuments({ status: "active" });
    
    // Users registered in last 30 days
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
    const newUsers = await User.countDocuments({
      createdAt: { $gte: thirtyDaysAgo }
    });

    res.json({
      success: true,
      stats: {
        total: totalUsers,
        admins: adminUsers,
        managers: managerUsers,
        users: regularUsers,
        members: memberUsers,
        stMembers,
        active: activeUsers,
        blocked: blockedUsers,
        newThisMonth: newUsers,
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: "Server error" });
  }
};
